<<<<<<< HEAD
def colorlist():
    colors = ['black',
              'pink',
              'white',
              'blue',
              'green',
              'lime',
              'red',
              'purple',
              'orange',
              'brown',
              'aqua',
              'cyan',
              'lightgreen',
              'lightblue',
              'lightred',
              'darkblue',
              'darkred',
              'darkpink',
              'lightorange',
              'darkorange',
              'gold',
              'silver',
              'magenta',
              'yellow',
              'gray',
              'lightgray',
              'darkgray']
=======
def colorlist():
    colors = ['black',
              'pink',
              'white',
              'blue',
              'green',
              'lime',
              'red',
              'purple',
              'orange',
              'brown',
              'aqua',
              'cyan',
              'lightgreen',
              'lightblue',
              'lightred',
              'darkblue',
              'darkred',
              'darkpink',
              'lightorange',
              'darkorange',
              'gold',
              'silver',
              'magenta',
              'yellow',
              'gray',
              'lightgray',
              'darkgray']
>>>>>>> ec58f8cda52865816fd5d8177f34b0bd8f33384e
    return colors